### ISSUE TITLE
exports missing autocomplete.css

### ISSUE THREAD

**Issue by grahamlangford** [kraaden/autocomplete#113] opened 2024-04-18 16:55 UTC
Is it possible to get the `autocomplete.css` added to the `exports` field in the package.json? 

I'm running into `Module not found: Error: Package path ./autocomplete.css is not exported from package` when building with webpack.

**Comment by denis-taran** [comment] 2024-04-18 22:31
@grahamlangford I added `autocomplete.css` to the export in `package.json` file. Let me know if the issue is fixed now.

**Comment by grahamlangford** [comment] 2024-04-19 13:49
That fixed it! Thanks for the quick turnaround!

**Closed as completed** 2024-04-19 13:50 UTC
