### ISSUE TITLE
(Bug) Re-rendering by pressing the up and down buttons

### ISSUE THREAD

**Issue by cvaize** [kraaden/autocomplete#45] opened 2020-01-16 13:37 UTC
Re-rendering by pressing the up and down buttons
https://drive.google.com/file/d/1rnIz_Cv-xK7wmXnrOs2D8whFlBRcITHS/view?usp=sharing

**Comment by denis-taran** [comment] 2020-01-20 04:52
Duplicate of #36

**Closed as completed by denis-taran** 2020-01-20 04:52 UTC
