### ISSUE TITLE
data handling problem

### ISSUE THREAD

**Issue by DarkPark** [kraaden/autocomplete#4] opened 2018-05-05 11:35 UTC
In the example data:

```js
var countries = [
    {label: 'United Kingdom', item: 'UK'},
    {label: 'United States', item: 'US'}
];
```

but what if I need something more complicated?

```js
var data = [
    {id: 8, name: 'some item name', title: 'some title', img: 'some image link', data: ['some linked data']}
];
```

on click `onSelect` will not give me the access to this data
it will give me nothing at all as it only works with property `item` and there is no such property

**Comment by denis-taran** [comment] 2018-05-05 12:34
Hi DarkPark,

Just call the `map` function before passing data to autocompleter and everything should work:

    var data = [
        {id: 08, name: 'Name A', title: 'Title A', img: 'imageA', data: ['dataA']},
        {id: 11, name: 'Name B', title: 'Title B', img: 'imageB', data: ['dataB']},
    ];
    
    autocomplete({
        input: document.getElementById("items"),
        fetch: function(text, update) {
            text = text.toLowerCase();
            var mapped = data.map(n => ({ label: n.name, item: n }));
            var suggestions = mapped.filter(n => n.label.toLowerCase().startsWith(text));
            update(suggestions);
        },
        onSelect: function(item) {
            alert("You selected an item with ID " + item.id);
        }
    });

You can test it here: https://fiddle.jshell.net/Ljaqr99r/1/

**Comment by DarkPark** [comment] 2018-05-05 13:41
sure it's possible
I've already used something like this
but it's not very productive to create unnecessary levels of abstractions - more complications, more memory
it would be nice not to demand this structure `{ label: "text", item: ... }` but to allow to pass any object
default render can expect this format but any custom one can handle another structure e.g. `{id: ..., title: ...}`
and `onSelect` will get this whole structure as it is
less hardcode, less magic

**Comment by denis-taran** [comment] 2018-08-07 17:18
The problem is resolved in the new version

    npm i --save-dev autocompleter@2.0.2

**Closed as completed by denis-taran** 2018-08-07 17:18 UTC

**Comment by DarkPark** [comment] 2018-08-07 18:17
thanks :+1:
